### ISSUE TITLE
Update README.md for Improved User Experience 📄

### ISSUE THREAD

**Issue by ATREAY** [openBookmarkz/ideas#10]
**Issue Description:**

We're looking to level up our repository by making the README.md more user-friendly. The goal is to provide a smoother onboarding experience for newcomers, helping them quickly understand what this repo is all about and guiding them through the process of handling issues and pull requests.

Here's what we're aiming for:

- **Clarity**: Ensure that anyone who lands on the README gets a crystal-clear picture of the repo's purpose and how they can contribute.
- **Walkthrough**: Include a step-by-step guide on how to tackle issues and submit pull requests.
- **User-Friendly**: Make it as newbie-friendly as possible so that contributors of all levels can dive right in.

Feel free to jump in and contribute to this effort.

**Comment by kera-cudmore** [comment]
Hey Atreay, 

would love to work on this issue if it's still available? 😊

**Comment by ATREAY** [comment]
Yes, it is! Here you go.

**Comment by ATREAY** [comment]
Big thanks @kera-cudmore for enhancing the user-friendliness of our README.md in openBookmarkz! Your contribution is highly appreciated.
